name: Publish

on:
  release:
    types:
      - published

jobs:
  release_zip_file:
    name: Run automations to build latest release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: ğŸ›ï¸ Checkout the repo
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744   # pinned v4

      - name: ğŸ Setup Python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9e   # pinned v5

      - name: ğŸ“ Update manifest version
        run: |
          VERSION="${{ github.event.release.tag_name }}"
          VERSION="${VERSION#v}"
          sed -i 's/"version": "[^"]*"/"version": "'"$VERSION"'"/' '${{ github.workspace }}/custom_components/gen24lpp/manifest.json'

      - name: ğŸ¤ Copy and Zip
        if: ${{ github.event_name == 'release' }}
        run: |
          cd '${{ github.workspace }}/custom_components/gen24lpp'
          zip gen24lpp.zip -r ./

      - name: â˜ï¸ Upload zip to release
        uses: softprops/action-gh-release@5e632badb6d78bbd66df7b366e2f1f00f7f1356e   # pinned v2.2.2
        if: ${{ github.event_name == 'release' }}
        with:
          files: "${{ github.workspace }}/custom_components/gen24lpp/gen24lpp.zip"
